[package]
edition = "2021"
name = "base-use"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo = "0.8.0"
yew = "0.19"
yew-infinite-for = {path = "../../"}
